version: "3.8"

networks:
  github:
    driver: "bridge"

services:
  runner:
    build:
      context: .
      dockerfile: ./debian-auth-token/Dockerfile
      args: 
        - RUNNER_VERSION=2.280.3
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - github
    env_file:
      - .env