name: runner

on:
  push:
    branches: [main]
    tags:
      - "*"
env:
  ORG: "dzirg44"
  GHCR_NAME: "github-action-runner"
  GITHUB_RUNNER_VERSION: "2.280.3"
  AWC_CLI_VERSION: "linux-x86_64-2.2.32"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v2

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${SOURCE_TAG} ${GITHUB_REPOSITORY} ${{ env.ORG }}"
          docker build -f debian-auth-token\Dockerfile \
            --build-arg GITHUB_RUNNER_VERSION=${{ env.GITHUB_RUNNER_VERSION }} \ 
            --build-arg AWC_CLI_VERSION=${{ env.AWC_CLI_VERSION }} \
            --tag ghcr.io/${{ env.ORG }}/${{ env.GHCR_NAME }}:${{ env.GITHUB_RUNNER_VERSION }}-${SOURCE_TAG} \
            .
          docker push ghcr.io/${{ env.ORG }}/${{ env.GHCR_NAME }}:${{ env.GITHUB_RUNNER_VERSION }}-${SOURCE_TAG}
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
